baseURL = "https://squaredcow.dev/"
languageCode = "en-us"
title = "squaredcow.dev"
theme = "PaperMod"
copyright = "© Luis Vaca"
enableRobotsTXT = true
enableEmoji = true

# New pagination format
[pagination]
pagerSize = 5

[params]
# Site info
description = "As a reader of many sorts, this is me moving towards the world of writing. With time I realized that each new learning takes time from us. The way I see it, the last piece to complete the exchange is to write it down. No more drafts left unfinished! That said, dear reader: Welcome!"
author = "Luis Vaca"

# Theme settings
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
dateFormat = "2006-01-02"

# Privacy and security settings
disableHLJS = false
disableSearchInJS = false
hideFooter = false

# Dark mode settings
defaultTheme = "auto" # can be "light", "dark", or "auto"
disableThemeToggle = false


# Home page settings
[params.homeInfoParams]
Title = "Hey there 👋"
Content = "Welcome to my blog! As a reader of many sorts, this is me moving towards the world of writing."

# Social icons - Professional only
[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/luivaca"

[[params.socialIcons]]
name = "github"
url = "https://github.com/squaredcow"

[[params.socialIcons]]
name = "buymeacoffee"
url = "https://coff.ee/squaredcow"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

# Menu configuration
[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "author"
name = "About"
url = "/author/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 40

[[menu.main]]
identifier = "license"
name = "License"
url = "/license/"
weight = 50

# Build settings
[build]
writeStats = true

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML", "RSS"]

[taxonomies]
tag = "tags"
category = "categories"

[privacy]
# Disable all external tracking and embeds for maximum privacy
[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = true
anonymizeIP = true
respectDoNotTrack = true

[privacy.instagram]
disable = true

[privacy.x]
disable = true

[privacy.twitter]
disable = true

[privacy.vimeo]
disable = true

[privacy.youtube]
disable = true
privacyEnhanced = true

[privacy.tikTok]
disable = true

[markup]
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
noClasses = false
style = "dracula"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
